# Generated by Django 3.0.7 on 2021-01-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_board_thumbnail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentalertcontent',
            name='board',
        ),
    ]
