# Generated by Django 3.0.7 on 2021-01-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_remove_commentalertcontent_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentalertcontent',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='board.Comment'),
        ),
    ]
